#!/bin/bash

# First argument is the input-file
JOB=$1

# Export variables
export G09=/opt/g09/g09
export PATH=/opt/g09:/opt/g09/bsd:$PATH
export GAUSS_EXEDIR=/opt/g09
#export GAUSS_SCRDIR=/home/$USER/scr
export GAUSS_SCRDIR=`pwd`


# # Check if local scratch directory exists
# if [ ! -d $GAUSS_SCRDIR ]; then
#     mkdir $GAUSS_SCRDIR
# fi

# Run g09
$G09 $JOB

# Clean-up local scratch-dir
# rm $GAUSS_SCRDIR/Gau*
